name: ffn_app
description: Une application Flutter pour suivre les exercices sportifs.
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  location: ^5.0.0
  provider: ^6.1.3